version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cats_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: npm run start:dev
    depends_on:
      - mongo
    networks:
      - cats-network

  mongo:
    image: mongo:5.0
    container_name: cats_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cats-network

volumes:
  mongo-data:

networks:
  cats-network: